### ISSUE TITLE
Broken Example

### ISSUE THREAD

**Issue by GregHilston** [dinubs/jam-api#19]
The example of targeting the URL "http://www.producthunt.com/jobs"

with  

{
  "title": "title",
  "companies": [{"elem": "ul.jobs li.job a", "link": "href", "name": "text"}],
  "company_descriptions": [{"elem": "ul.jobs li.job .description", "name": "text"}]
}

Has valid JSON, but no longer populates companies or companies_descriptions

**Comment by gavindinubilo** [comment]
I'll come up with a better example over the weekend, if you have any suggestions for sites that could be a good example let me know. Preferably one whose content doesn't change too often.

**Comment by JamesDonnelly** [comment]
Assuming this was once fixed: this is broken again.

**Comment by dinubs** [comment]
I changed the examples to be to a site that I control, (www.gavin.codes). I believe I forgot to close this out after updating the examples.
